
version: '3.8'

services:

  microservicio-vehiculos-livianos:
    build:
      context: ./MicroservicioVehiculos
      dockerfile: Dockerfile
    container_name: microservicio-vehiculos-livianos
    ports:
      - "5004:8080"
      - "5005:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=10.0.0.5;Port=5432;Database=CombustibleDB;Username=postgres;Password=200232
    networks:
      - red-ms

  microservicio-asignacion-rutas-livianos:
    build:
      context: ./MicroservicioAsignacionRutas
      dockerfile: Dockerfile
    container_name: microservicio-asignacion-rutas-livianos
    ports:
      - "5006:8080"
      - "5007:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=10.0.0.5;Port=5432;Database=CombustibleDB;Username=postgres;Password=200232
    networks:
      - red-ms

  microservicio-consumo-combustible-livianos:
    build:
      context: ./MicroservicioConsumoCombustible
      dockerfile: Dockerfile
    container_name: microservicio-consumo-combustible-livianos
    ports:
      - "5028:8080"
      - "5029:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=10.0.0.5;Port=5432;Database=CombustibleDB;Username=postgres;Password=200232
    networks:
      - red-ms


networks:
  red-ms:
    external: true
